name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    environment: test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: ${{ vars.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ vars.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ vars.POSTGRES_DB }}
          POSTGRES_PORT: ${{ vars.POSTGRES_PORT }}
        ports:
          - ${{ vars.POSTGRES_PORT }}:${{ vars.POSTGRES_PORT }}
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.4'
      - name: Install zsh
        run: sudo apt-get update; sudo apt-get install zsh
      - name: build
        run: go build -o main ./cmd/app
      - name: change permissions
        run: chmod +x main
      - name: start server
        run: ./main &
      - name: healthcheck
        run: timeout 60s zsh -c 'while [[ ''$(curl -s -o /dev/null -w ''%{http_code}'' localhost:${{ vars.APP_PORT }})'' != "200" ]]; do echo "Waiting for container to be healthy..."; sleep 2; done'
        shell: zsh {0}
      - name: test
        run: go test -v ./cmd/tests
